security:
    encoders:
        Purmeo\EshopBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: PurmeoEshopBundle:User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: purmeo_eshop_login
                check_path: purmeo_eshop_login_check
                default_target_path: /user
            logout:
                path: purmeo_eshop_logout
                target: /