<?php

namespace Purmeo\EshopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Purmeo\EshopBundle\Entity\Address;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository {

    public function createAddress2($user, $form, $type, $em) {
        $address = new Address();
        $address->setTitle($form->getTitle());
        $address->setFirstname($form->getFirstname());
        $address->setLastname($form->getLastname());
        $address->setStreet($form->getStreet());
        $address->setNumber($form->getNumber());
        $address->setOtherInfo($form->getOtherInfo() ? $form->getOtherInfo() : '');
        $address->setCity($form->getCity());
        $address->setZipcode($form->getZipcode());
        $address->setPhone($form->getTelephone() ? $form->getTelephone() : '');
        $address->setCountry($form->getCountry());
        $address->setType($type);
        $address->setUser($user);
        $em->persist($address);
        $em->flush();

        return $address;
    }

    public function createAddress($user, $pay, $type, $em) {
        $address = new Address();
        $address->setTitle($pay->getBillingTitle());
        $address->setFirstname($pay->getBillingFirstname());
        $address->setLastname($pay->getBillingLastname());
        $address->setStreet($pay->getBillingStreet());
        $address->setNumber($pay->getBillingNumber());
        $address->setOtherInfo($pay->getBillingOtherInfo() ? $pay->getBillingOtherInfo() : '');
        $address->setCity($pay->getBillingCity());
        $address->setZipcode($pay->getBillingZipcode());
        $address->setPhone($pay->getBillingTelephone() ? $pay->getBillingTelephone() : '');
        $address->setCountry($pay->getBillingCountry());
        $address->setType($type);
        $address->setUser($user);
        $em->persist($address);
        $em->flush();

        return $address;
    }

}
