<?php

namespace Purmeo\EshopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Purmeo\EshopBundle\Entity\Checks;

/**
 * ChecksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecksRepository extends EntityRepository {

    public function createCheck($form, $order) {

        $em = $this->getEntityManager();
        
        $check = new Checks();
        $check->setGender($form->getGender());
        $check->setWeight($form->getWeight());
        $check->setHeight($form->getHeight());
        $check->setDay($form->getDay());
        $check->setMonth($form->getMonth());
        $check->setYear($form->getYear());
        $check->setSport($form->getSport());
        $check->setSmoker($form->getSmoker());
        $check->setDrink($form->getDrink());
        $check->setDream($form->getDream());
        $check->setStress($form->getStress());
        $check->setPregnant($form->getPregnant());
        $check->setGrain($form->getGrain());
        $check->setFruit($form->getFruit());
        $check->setSalad($form->getSalad());
        $check->setMeat($form->getMeat());
        $check->setFish($form->getFish());
        $check->setMilk($form->getMilk());
        $check->setWater($form->getWater());
        $check->setFastfood($form->getFastfood());
        $check->setSweets($form->getSweets());
        $check->setDiet($form->getDiet());
        $check->setOil($form->getOil());
        $check->setProblems($form->getProblems());
        $check->setAgree($form->getAgree());

        $em->persist($check);
        $em->flush();
    }

}
