<?php

namespace Purmeo\EshopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository {

    public function getProducts() {
        $query = $this->createQueryBuilder('a')
                ->select('a')
                ->andWhere('a.actived = 1')
                ->addOrderBy('a.created', 'DESC');

        return $query->getQuery()->getResult();
    }

}
