<?php

namespace Purmeo\EshopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Purmeo\EshopBundle\Entity\Subscribes;

/**
 * SubscribesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribesRepository extends EntityRepository {

    public function addSubscribe($email, $event) {
        $em = $this->getEntityManager();

        $subscribe = new Subscribes;
        $subscribe->setEmail($email);
        $subscribe->setEvent($event);

        $em->persist($subscribe);
        $em->flush();
        
        return true;
    }

}
